### ISSUE TITLE
train should choo choo

### ISSUE THREAD

**Issue by richaagarwal** [thisisparker/choochoobot#6]
currently it does not

**Comment by thisisparker** [comment]
I've considered this a bit. Three components of the train that would add some verisimilitude are tracks (visually a #, audibly the chugga chugga), the whistle (presumably present on the steam locomotive emoji, but audibly a choo choo), and the steam release.

I'm not interested in adding audio components, so that rules out most of the chugga chugga and the choo choo. I haven't found a visual emoji solution that looks compellingly like tracks, and I would rather not imply the right end of the frame at all if I can help it (outside the seashore on the beach and the borders of the special scenes).

That leaves the steam release, which could probably be represented by :thought_balloon:. The issue there is spacing: unless I switch to a wider space character of standard width, I can't readily conceive of a safe way to accurately place one object directly above another where leading character may be spaces or emoji.
